# Generated by Django 4.2.2 on 2023-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
